version: '3.8'
services:
  backend:
    image: radovodoo/company-backend:latest # Pakai image dari Docker Hub
    ports:
      - "8080:8080"
    # HAPUS baris 'build: ./backend' karena di VM tidak ada source code

  frontend:
    image: radovodoo/company-frontend:latest # Pakai image dari Docker Hub
    ports:
      - "80:80"
    # HAPUS baris 'build: ./frontend'