version: '3.8'

services:
  # Bagian Backend
  backend:
    image: radovodoo/company-backend:latest  # GUNAKAN IMAGE, BUKAN BUILD
    container_name: company_be
    ports:
      - "8080:8080"
    restart: always

  # Bagian Frontend
  frontend:
    image: radovodoo/company-frontend:latest # GUNAKAN IMAGE, BUKAN BUILD
    container_name: company_fe
    ports:
      - "80:80"
    restart: always
    # PENTING: Hapus baris 'volumes' jika file nginx.conf tidak ada di VM