version: '3.8'

services:
  backend:
    image: radovodoo/company-backend:latest
    container_name: company_be
    # Port 8080 dihapus dari public (opsional tapi disarankan agar aman)
    # ports: 
    #   - "8080:8080"
    restart: always
    networks:
      - company-network

  frontend:
    image: radovodoo/company-frontend:latest
    container_name: company_fe
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
    depends_on:
      - backend
    networks:
      - company-network

networks:
  company-network:
    driver: bridge