name: Backend Deploy

on:
  push:
    paths:
      - "backend/**"
  workflow_dispatch:
    

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Debug files
        run: ls -R

      - name: Copy project to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          source: "."
          target: "/home/${{ secrets.VM_USER }}/app"

      - name: Deploy container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd ~/app
            docker compose up -d --build