name: Frontend Deploy

on:
  push:
    paths:
      - "frontend/**"
  workflow_dispatch:

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build React
        run: |
          cd frontend/react-app
          npm install
          npm run build

      - name: Copy frontend to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          source: "frontend"
          target: "/home/${{ secrets.VM_USER }}/app"

      - name: Restart containers
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd ~/app
            docker compose build frontend
            docker compose up -d frontend nginx