name: Frontend CI/CD

on:
  push:
    paths:
      - "frontend/**"
  workflow_dispatch:
    

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies & Build React
        run: |
          cd frontend/react-app
          npm install
          npm run build

      - name: Copy Build to Azure VM via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "frontend/react-app/build"
          target: "/home/${{ secrets.VM_USER }}/app"

      - name: Restart Nginx via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl restart nginx